/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Category = { 'gasCylinder' : null } |
  { 'cookHelperHonorarium' : null } |
  { 'other' : null } |
  { 'sugar' : null } |
  { 'cookingConversion' : null } |
  { 'milkWarmingHonorarium' : null };
export interface DashboardSummary {
  'todayExpenses' : bigint,
  'cashBalance' : bigint,
  'bankBalance' : bigint,
  'todayReceipts' : bigint,
}
export type Mode = { 'bank' : null } |
  { 'cash' : null };
export interface OpeningBalance { 'bankAmount' : bigint, 'cashAmount' : bigint }
export interface Summary {
  'bankClosing' : bigint,
  'cashReceived' : bigint,
  'bankSpent' : bigint,
  'bankReceived' : bigint,
  'cashSpent' : bigint,
  'cashOpening' : bigint,
  'bankOpening' : bigint,
  'cashClosing' : bigint,
}
export interface Transaction {
  'id' : bigint,
  'transactionType' : TransactionType,
  'date' : string,
  'mode' : Mode,
  'createdAt' : bigint,
  'description' : string,
  'voucherNumber' : string,
  'category' : Category,
  'amount' : bigint,
}
export type TransactionType = { 'expense' : null } |
  { 'receipt' : null };
export interface TransactionUpdate {
  'transactionType' : TransactionType,
  'date' : string,
  'mode' : Mode,
  'description' : string,
  'voucherNumber' : string,
  'category' : Category,
  'amount' : bigint,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addTransaction' : ActorMethod<[Transaction], bigint>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteTransaction' : ActorMethod<[bigint], undefined>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDashboardSummary' : ActorMethod<[], DashboardSummary>,
  'getOpeningBalance' : ActorMethod<[], OpeningBalance>,
  'getSummary' : ActorMethod<[string, string], Summary>,
  'getTransaction' : ActorMethod<[bigint], Transaction>,
  'getTransactions' : ActorMethod<
    [
      [] | [string],
      [] | [string],
      [] | [Category],
      [] | [TransactionType],
      [] | [Mode],
    ],
    Array<Transaction>
  >,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'setOpeningBalance' : ActorMethod<[OpeningBalance], undefined>,
  'updateTransaction' : ActorMethod<[bigint, TransactionUpdate], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];