/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const TransactionType = IDL.Variant({
  'expense' : IDL.Null,
  'receipt' : IDL.Null,
});
export const Mode = IDL.Variant({ 'bank' : IDL.Null, 'cash' : IDL.Null });
export const Category = IDL.Variant({
  'gasCylinder' : IDL.Null,
  'cookHelperHonorarium' : IDL.Null,
  'other' : IDL.Null,
  'sugar' : IDL.Null,
  'cookingConversion' : IDL.Null,
  'milkWarmingHonorarium' : IDL.Null,
});
export const Transaction = IDL.Record({
  'id' : IDL.Nat,
  'transactionType' : TransactionType,
  'date' : IDL.Text,
  'mode' : Mode,
  'createdAt' : IDL.Int,
  'description' : IDL.Text,
  'voucherNumber' : IDL.Text,
  'category' : Category,
  'amount' : IDL.Nat,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const DashboardSummary = IDL.Record({
  'todayExpenses' : IDL.Nat,
  'cashBalance' : IDL.Nat,
  'bankBalance' : IDL.Nat,
  'todayReceipts' : IDL.Nat,
});
export const OpeningBalance = IDL.Record({
  'bankAmount' : IDL.Nat,
  'cashAmount' : IDL.Nat,
});
export const Summary = IDL.Record({
  'bankClosing' : IDL.Nat,
  'cashReceived' : IDL.Nat,
  'bankSpent' : IDL.Nat,
  'bankReceived' : IDL.Nat,
  'cashSpent' : IDL.Nat,
  'cashOpening' : IDL.Nat,
  'bankOpening' : IDL.Nat,
  'cashClosing' : IDL.Nat,
});
export const TransactionUpdate = IDL.Record({
  'transactionType' : TransactionType,
  'date' : IDL.Text,
  'mode' : Mode,
  'description' : IDL.Text,
  'voucherNumber' : IDL.Text,
  'category' : Category,
  'amount' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addTransaction' : IDL.Func([Transaction], [IDL.Nat], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteTransaction' : IDL.Func([IDL.Nat], [], []),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDashboardSummary' : IDL.Func([], [DashboardSummary], ['query']),
  'getOpeningBalance' : IDL.Func([], [OpeningBalance], ['query']),
  'getSummary' : IDL.Func([IDL.Text, IDL.Text], [Summary], ['query']),
  'getTransaction' : IDL.Func([IDL.Nat], [Transaction], ['query']),
  'getTransactions' : IDL.Func(
      [
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(Category),
        IDL.Opt(TransactionType),
        IDL.Opt(Mode),
      ],
      [IDL.Vec(Transaction)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'setOpeningBalance' : IDL.Func([OpeningBalance], [], []),
  'updateTransaction' : IDL.Func([IDL.Nat, TransactionUpdate], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const TransactionType = IDL.Variant({
    'expense' : IDL.Null,
    'receipt' : IDL.Null,
  });
  const Mode = IDL.Variant({ 'bank' : IDL.Null, 'cash' : IDL.Null });
  const Category = IDL.Variant({
    'gasCylinder' : IDL.Null,
    'cookHelperHonorarium' : IDL.Null,
    'other' : IDL.Null,
    'sugar' : IDL.Null,
    'cookingConversion' : IDL.Null,
    'milkWarmingHonorarium' : IDL.Null,
  });
  const Transaction = IDL.Record({
    'id' : IDL.Nat,
    'transactionType' : TransactionType,
    'date' : IDL.Text,
    'mode' : Mode,
    'createdAt' : IDL.Int,
    'description' : IDL.Text,
    'voucherNumber' : IDL.Text,
    'category' : Category,
    'amount' : IDL.Nat,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const DashboardSummary = IDL.Record({
    'todayExpenses' : IDL.Nat,
    'cashBalance' : IDL.Nat,
    'bankBalance' : IDL.Nat,
    'todayReceipts' : IDL.Nat,
  });
  const OpeningBalance = IDL.Record({
    'bankAmount' : IDL.Nat,
    'cashAmount' : IDL.Nat,
  });
  const Summary = IDL.Record({
    'bankClosing' : IDL.Nat,
    'cashReceived' : IDL.Nat,
    'bankSpent' : IDL.Nat,
    'bankReceived' : IDL.Nat,
    'cashSpent' : IDL.Nat,
    'cashOpening' : IDL.Nat,
    'bankOpening' : IDL.Nat,
    'cashClosing' : IDL.Nat,
  });
  const TransactionUpdate = IDL.Record({
    'transactionType' : TransactionType,
    'date' : IDL.Text,
    'mode' : Mode,
    'description' : IDL.Text,
    'voucherNumber' : IDL.Text,
    'category' : Category,
    'amount' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addTransaction' : IDL.Func([Transaction], [IDL.Nat], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteTransaction' : IDL.Func([IDL.Nat], [], []),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDashboardSummary' : IDL.Func([], [DashboardSummary], ['query']),
    'getOpeningBalance' : IDL.Func([], [OpeningBalance], ['query']),
    'getSummary' : IDL.Func([IDL.Text, IDL.Text], [Summary], ['query']),
    'getTransaction' : IDL.Func([IDL.Nat], [Transaction], ['query']),
    'getTransactions' : IDL.Func(
        [
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(Category),
          IDL.Opt(TransactionType),
          IDL.Opt(Mode),
        ],
        [IDL.Vec(Transaction)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'setOpeningBalance' : IDL.Func([OpeningBalance], [], []),
    'updateTransaction' : IDL.Func([IDL.Nat, TransactionUpdate], [], []),
  });
};

export const init = ({ IDL }) => { return []; };