/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface DashboardSummary {
    todayExpenses: bigint;
    cashBalance: bigint;
    bankBalance: bigint;
    todayReceipts: bigint;
}
export interface TransactionUpdate {
    transactionType: TransactionType;
    date: string;
    mode: Mode;
    description: string;
    voucherNumber: string;
    category: Category;
    amount: bigint;
}
export interface Summary {
    bankClosing: bigint;
    cashReceived: bigint;
    bankSpent: bigint;
    bankReceived: bigint;
    cashSpent: bigint;
    cashOpening: bigint;
    bankOpening: bigint;
    cashClosing: bigint;
}
export interface OpeningBalance {
    bankAmount: bigint;
    cashAmount: bigint;
}
export interface Transaction {
    id: bigint;
    transactionType: TransactionType;
    date: string;
    mode: Mode;
    createdAt: bigint;
    description: string;
    voucherNumber: string;
    category: Category;
    amount: bigint;
}
export enum Category {
    gasCylinder = "gasCylinder",
    cookHelperHonorarium = "cookHelperHonorarium",
    other = "other",
    sugar = "sugar",
    cookingConversion = "cookingConversion",
    milkWarmingHonorarium = "milkWarmingHonorarium"
}
export enum Mode {
    bank = "bank",
    cash = "cash"
}
export enum TransactionType {
    expense = "expense",
    receipt = "receipt"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addTransaction(transaction: Transaction): Promise<bigint>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    deleteTransaction(id: bigint): Promise<void>;
    getCallerUserRole(): Promise<UserRole>;
    getDashboardSummary(): Promise<DashboardSummary>;
    getOpeningBalance(): Promise<OpeningBalance>;
    getSummary(fromDate: string, toDate: string): Promise<Summary>;
    getTransaction(id: bigint): Promise<Transaction>;
    getTransactions(fromDate: string | null, toDate: string | null, category: Category | null, transactionType: TransactionType | null, mode: Mode | null): Promise<Array<Transaction>>;
    isCallerAdmin(): Promise<boolean>;
    setOpeningBalance(balance: OpeningBalance): Promise<void>;
    updateTransaction(id: bigint, transaction: TransactionUpdate): Promise<void>;
}
import type { Category as _Category, Mode as _Mode, Transaction as _Transaction, TransactionType as _TransactionType, TransactionUpdate as _TransactionUpdate, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addTransaction(arg0: Transaction): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addTransaction(to_candid_Transaction_n1(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addTransaction(to_candid_Transaction_n1(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n9(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n9(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async deleteTransaction(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteTransaction(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteTransaction(arg0);
            return result;
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDashboardSummary(): Promise<DashboardSummary> {
        if (this.processError) {
            try {
                const result = await this.actor.getDashboardSummary();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDashboardSummary();
            return result;
        }
    }
    async getOpeningBalance(): Promise<OpeningBalance> {
        if (this.processError) {
            try {
                const result = await this.actor.getOpeningBalance();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOpeningBalance();
            return result;
        }
    }
    async getSummary(arg0: string, arg1: string): Promise<Summary> {
        if (this.processError) {
            try {
                const result = await this.actor.getSummary(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSummary(arg0, arg1);
            return result;
        }
    }
    async getTransaction(arg0: bigint): Promise<Transaction> {
        if (this.processError) {
            try {
                const result = await this.actor.getTransaction(arg0);
                return from_candid_Transaction_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTransaction(arg0);
            return from_candid_Transaction_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTransactions(arg0: string | null, arg1: string | null, arg2: Category | null, arg3: TransactionType | null, arg4: Mode | null): Promise<Array<Transaction>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTransactions(to_candid_opt_n21(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n21(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n22(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n23(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n24(this._uploadFile, this._downloadFile, arg4));
                return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTransactions(to_candid_opt_n21(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n21(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n22(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n23(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n24(this._uploadFile, this._downloadFile, arg4));
            return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async setOpeningBalance(arg0: OpeningBalance): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setOpeningBalance(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setOpeningBalance(arg0);
            return result;
        }
    }
    async updateTransaction(arg0: bigint, arg1: TransactionUpdate): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTransaction(arg0, to_candid_TransactionUpdate_n26(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTransaction(arg0, to_candid_TransactionUpdate_n26(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_Category_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Category): Category {
    return from_candid_variant_n20(_uploadFile, _downloadFile, value);
}
function from_candid_Mode_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Mode): Mode {
    return from_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function from_candid_TransactionType_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TransactionType): TransactionType {
    return from_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function from_candid_Transaction_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Transaction): Transaction {
    return from_candid_record_n14(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function from_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    transactionType: _TransactionType;
    date: string;
    mode: _Mode;
    createdAt: bigint;
    description: string;
    voucherNumber: string;
    category: _Category;
    amount: bigint;
}): {
    id: bigint;
    transactionType: TransactionType;
    date: string;
    mode: Mode;
    createdAt: bigint;
    description: string;
    voucherNumber: string;
    category: Category;
    amount: bigint;
} {
    return {
        id: value.id,
        transactionType: from_candid_TransactionType_n15(_uploadFile, _downloadFile, value.transactionType),
        date: value.date,
        mode: from_candid_Mode_n17(_uploadFile, _downloadFile, value.mode),
        createdAt: value.createdAt,
        description: value.description,
        voucherNumber: value.voucherNumber,
        category: from_candid_Category_n19(_uploadFile, _downloadFile, value.category),
        amount: value.amount
    };
}
function from_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    expense: null;
} | {
    receipt: null;
}): TransactionType {
    return "expense" in value ? TransactionType.expense : "receipt" in value ? TransactionType.receipt : value;
}
function from_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bank: null;
} | {
    cash: null;
}): Mode {
    return "bank" in value ? Mode.bank : "cash" in value ? Mode.cash : value;
}
function from_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    gasCylinder: null;
} | {
    cookHelperHonorarium: null;
} | {
    other: null;
} | {
    sugar: null;
} | {
    cookingConversion: null;
} | {
    milkWarmingHonorarium: null;
}): Category {
    return "gasCylinder" in value ? Category.gasCylinder : "cookHelperHonorarium" in value ? Category.cookHelperHonorarium : "other" in value ? Category.other : "sugar" in value ? Category.sugar : "cookingConversion" in value ? Category.cookingConversion : "milkWarmingHonorarium" in value ? Category.milkWarmingHonorarium : value;
}
function from_candid_vec_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Transaction>): Array<Transaction> {
    return value.map((x)=>from_candid_Transaction_n13(_uploadFile, _downloadFile, x));
}
function to_candid_Category_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Category): _Category {
    return to_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function to_candid_Mode_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Mode): _Mode {
    return to_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function to_candid_TransactionType_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TransactionType): _TransactionType {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_TransactionUpdate_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TransactionUpdate): _TransactionUpdate {
    return to_candid_record_n27(_uploadFile, _downloadFile, value);
}
function to_candid_Transaction_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Transaction): _Transaction {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Category | null): [] | [_Category] {
    return value === null ? candid_none() : candid_some(to_candid_Category_n7(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TransactionType | null): [] | [_TransactionType] {
    return value === null ? candid_none() : candid_some(to_candid_TransactionType_n3(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Mode | null): [] | [_Mode] {
    return value === null ? candid_none() : candid_some(to_candid_Mode_n5(_uploadFile, _downloadFile, value));
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    transactionType: TransactionType;
    date: string;
    mode: Mode;
    createdAt: bigint;
    description: string;
    voucherNumber: string;
    category: Category;
    amount: bigint;
}): {
    id: bigint;
    transactionType: _TransactionType;
    date: string;
    mode: _Mode;
    createdAt: bigint;
    description: string;
    voucherNumber: string;
    category: _Category;
    amount: bigint;
} {
    return {
        id: value.id,
        transactionType: to_candid_TransactionType_n3(_uploadFile, _downloadFile, value.transactionType),
        date: value.date,
        mode: to_candid_Mode_n5(_uploadFile, _downloadFile, value.mode),
        createdAt: value.createdAt,
        description: value.description,
        voucherNumber: value.voucherNumber,
        category: to_candid_Category_n7(_uploadFile, _downloadFile, value.category),
        amount: value.amount
    };
}
function to_candid_record_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    transactionType: TransactionType;
    date: string;
    mode: Mode;
    description: string;
    voucherNumber: string;
    category: Category;
    amount: bigint;
}): {
    transactionType: _TransactionType;
    date: string;
    mode: _Mode;
    description: string;
    voucherNumber: string;
    category: _Category;
    amount: bigint;
} {
    return {
        transactionType: to_candid_TransactionType_n3(_uploadFile, _downloadFile, value.transactionType),
        date: value.date,
        mode: to_candid_Mode_n5(_uploadFile, _downloadFile, value.mode),
        description: value.description,
        voucherNumber: value.voucherNumber,
        category: to_candid_Category_n7(_uploadFile, _downloadFile, value.category),
        amount: value.amount
    };
}
function to_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TransactionType): {
    expense: null;
} | {
    receipt: null;
} {
    return value == TransactionType.expense ? {
        expense: null
    } : value == TransactionType.receipt ? {
        receipt: null
    } : value;
}
function to_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Mode): {
    bank: null;
} | {
    cash: null;
} {
    return value == Mode.bank ? {
        bank: null
    } : value == Mode.cash ? {
        cash: null
    } : value;
}
function to_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Category): {
    gasCylinder: null;
} | {
    cookHelperHonorarium: null;
} | {
    other: null;
} | {
    sugar: null;
} | {
    cookingConversion: null;
} | {
    milkWarmingHonorarium: null;
} {
    return value == Category.gasCylinder ? {
        gasCylinder: null
    } : value == Category.cookHelperHonorarium ? {
        cookHelperHonorarium: null
    } : value == Category.other ? {
        other: null
    } : value == Category.sugar ? {
        sugar: null
    } : value == Category.cookingConversion ? {
        cookingConversion: null
    } : value == Category.milkWarmingHonorarium ? {
        milkWarmingHonorarium: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
